services:
  postgres-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=admin
    restart: always
    expose:
      - 5432
    ports:
      - "5433:5432"
    hostname: postgres-db
    networks:
      - taco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  postgrest-a:
    container_name: postgrest-a
    image: postgrest/postgrest:latest
    ports:
      - "3001:3000"
    environment:
      - PGRST_DB_URI=postgres://admin:admin@postgres-db:5432/postgres-db
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=admin
      - PGRST_LOG_LEVEL=info
    restart: on-failure
    networks:
      - taco
    depends_on:
      postgres-db:
        condition: service_healthy

  postgrest-b:
    container_name: postgrest-b
    image: postgrest/postgrest:latest
    ports:
      - "3002:3000"
    environment:
      - PGRST_DB_URI=postgres://admin:admin@postgres-db:5432/postgres-db
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=admin
      - PGRST_LOG_LEVEL=info
    restart: on-failure
    networks:
      - taco
    depends_on:
      postgres-db:
        condition: service_healthy

  nginx-loadbalancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgrest-a
      - postgrest-b
    networks:
      - taco

networks:
  taco:

volumes:
  db_data: